### ISSUE TITLE
Bug: NoneType on getPrimaryPixels

### ISSUE THREAD

**Issue by joshmoore** [ome/figure#93]
```
15:07 ERROR: demo OMEROweb_request:
2015-07-03 14:07:22,265 ERROR [                          django.request] (proc.24409) handle_uncaught_exception:226 Internal Server Error: /figure/imgData/52/
Traceback (most recent call last):
  File "/home/demo/OMERO.server-5.1.2-ice35-b45/lib/python/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/demo/OMERO.server-5.1.2-ice35-b45/lib/python/omeroweb/decorators.py", line 471, in wrapped
    retval = f(request, *args, **kwargs)
  File "/home/demo/web-extensions/figure/views.py", line 118, in imgData_json
    px = image.getPrimaryPixels().getPhysicalSizeX()
AttributeError: 'NoneType' object has no attribute 'getPrimaryPixels'
```

**Comment by will-moore** [comment]
This has been fixed by https://github.com/ome/figure/pull/108
